name: Test

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: latest
          platform: x64

      - name: Configure
        run: |
          cmake -B build -S . \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Run tests (with output)
        run: |
          cd build
          ctest --output-on-failure --no-tests=error \
                --output-junit test-results.xml

      - name: Upload test results (artifact)
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: build/test-results.xml

      - name: Publish test report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: CTest Results
          path: build/test-results.xml
          reporter: java-junit